#/usr/bin/env sh
cat Core/Core.js  > mootools_1.1_to_1.2_upgrade_helper.js
cat Core/Browser.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Native/Array.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Native/Function.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Native/Hash.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Class/Class.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Element/Element.Dimensions.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Element/Element.Event.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Element/Element.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Element/Element.Style.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Fx/Fx.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Fx/Fx.Tween.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Fx/Fx.Morph.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Fx/Fx.Scroll.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Request/Request.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Request/Request.JSON.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Utilities/Cookie.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Utilities/JSON.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Utilities/Selectors.js  >> mootools_1.1_to_1.2_upgrade_helper.js
cat Plugins/Tips.js  >> mootools_1.1_to_1.2_upgrade_helper.js
